# oauth2-proxy reverse-proxy: X-Forwarded-* | auth_request: X-Auth-Request-*
map $http_x_auth_request_user $sp_auth_user {
    default $http_x_auth_request_user;
    ""      $http_x_forwarded_user;
}

map $http_x_auth_request_email $sp_auth_email {
    default $http_x_auth_request_email;
    ""      $http_x_forwarded_email;
}

map $http_x_auth_request_groups $sp_auth_groups {
    default $http_x_auth_request_groups;
    ""      $http_x_forwarded_groups;
}

map $http_x_forwarded_access_token $sp_access_token {
    default $http_x_forwarded_access_token;
    ""      $http_x_auth_request_access_token;
}
