system:
  customHTMLFiles: true
  enableAnalytics: false
  showUpdate: false
  showUpdateOnlyAdmin: false
  googlevisibility: false
  defaultLocale: tr-TR
  enableUrlToPDF: true
legal:
  termsAndConditions: ''
  privacyPolicy: ''
  accessibilityStatement: ''
  cookiePolicy: ''
  impressum: ''
premium:
  enabled: true
metrics:
  enabled: false
ui:
  appNameNavbar: SecuriPDF
  logoStyle: classic
  defaultHideUnavailableTools: true
  languages:
  - tr_TR
  - en_GB
endpoints:
  toRemove:
  - adjust-contrast
  - automate
  - delete-fields
  - dev-airgapped-docs
  - dev-api-docs
  - dev-folder-scanning-docs
  - dev-sso-guide-docs
  - fields
  - fill
  - handleData
  - json-to-pdf
  - modify-fields
  - multi-tool
  - pdf-to-json
  - pdf-to-rtf
  - pdf-to-video
  - pipeline
  - redact
  - remove-annotations
  - show-javascript
  groupsToRemove: []
